version: '1.0.0'

services:
  redis: 
    image: redis:7
    ports: 
     - '6379:6379'
    expose:
     - '6379'

  db:
    image: postgres:15
    environment:
      TZ: America/Maceio
      POSTGRES_PASSWORD: alexnunes12
      POSTGRES_USER: postgres
    ports:
     - '5432:5432'
    expose: 
     - '5432'
  
  web: 
    build: .
    entrypoint: config/setup_app.sh
    command: bash -c "rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: America/Maceio
    env_file:
     - ./.env.development
    ports:
     - '3000:3000'
    volumes:
     - .:/home/kanban_docker/web

  worker:
    build: 
      context: .
      dockerfile: ./worker/Dockerfile
    environment:
      TZ: America/Maceio
    env_file:
     - ./.env.development
    volumes:
     - .:/home/kanban_docker/web
