default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>


development:
  <<: *default
  database: docker_development

 
test:
  <<: *default
  database: docker_teste

production:
  <<: *default
  database: docker_production
  username: kanban
  password: <%= ENV["SURVEY5_DATABASE_PASSWORD"] %>
